### ISSUE TITLE
draft - closed

### ISSUE THREAD

**Issue by irinikp** [asmblah/php-amqp-compat#1]

**Comment by irinikp** [comment]
https://github.com/asmblah/php-amqp-compat/blob/9957a6d7f1f5f3e091f61a22dacbb1d54cf1b308/src/Amqp/AMQPBasicProperties.php#L23
Why are these properties nullable? I don't see where they can be set to `null`

**Comment by irinikp** [comment]
https://github.com/php-amqp/php-amqp/blob/a757b6657eedbbe3802756720f78f33e058d8d66/stubs/AMQPBasicProperties.php#L28C19-L28C19
On the file you're linking, this defaults to `2`

**Comment by asmblah** [comment]
See https://github.com/asmblah/php-amqp-compat/pull/2.
